//This file was generated by generateIconImports.mjs

import ArchaicPetra from '/public/icons/artifacts/Archaic Petra.png';
import BlizzardStrayer from '/public/icons/artifacts/Blizzard Strayer.png';
import BloodstainedChivalry from '/public/icons/artifacts/Bloodstained Chivalry.png';
import CrimsonWitchOfFlames from '/public/icons/artifacts/Crimson Witch Of Flames.png';
import DeepwoodMemories from '/public/icons/artifacts/Deepwood Memories.png';
import DesertPavilionChronicle from '/public/icons/artifacts/Desert Pavilion Chronicle.png';
import EchoesOfAnOffering from '/public/icons/artifacts/Echoes Of An Offering.png';
import EmblemOfSeveredFate from '/public/icons/artifacts/Emblem Of Severed Fate.png';
import FlowerOfParadiseLost from '/public/icons/artifacts/Flower Of Paradise Lost.png';
import FragmentOfHarmonicWhimsy from '/public/icons/artifacts/Fragment Of Harmonic Whimsy.png';
import GildedDreams from '/public/icons/artifacts/Gilded Dreams.png';
import GladiatorsFinale from '/public/icons/artifacts/Gladiator\'s Finale.png';
import GoldenTroupe from '/public/icons/artifacts/Golden Troupe.png';
import HeartOfDepth from '/public/icons/artifacts/Heart Of Depth.png';
import HuskOfOpulentDreams from '/public/icons/artifacts/Husk Of Opulent Dreams.png';
import Instructor from '/public/icons/artifacts/Instructor.webp';
import Lavawalker from '/public/icons/artifacts/Lavawalker.png';
import MaidenBeloved from '/public/icons/artifacts/Maiden Beloved.png';
import MarechausseeHunter from '/public/icons/artifacts/Marechaussee Hunter.png';
import NighttimeWhispersInTheEchoingWoods from '/public/icons/artifacts/Nighttime Whispers In The Echoing Woods.png';
import NoblesseOblige from '/public/icons/artifacts/Noblesse Oblige.png';
import NymphsDream from '/public/icons/artifacts/Nymph\'s Dream.png';
import ObsidianCodex from '/public/icons/artifacts/Obsidian Codex.png';
import OceanHuedClam from '/public/icons/artifacts/Ocean-Hued Clam.png';
import PaleFlame from '/public/icons/artifacts/Pale Flame.png';
import RetracingBolide from '/public/icons/artifacts/Retracing Bolide.png';
import ScrollOfTheHeroOfCinderCity from '/public/icons/artifacts/Scroll Of The Hero Of Cinder City.png';
import ShimenawasReminiscence from '/public/icons/artifacts/Shimenawa\'s Reminiscence.png';
import SongOfDaysPast from '/public/icons/artifacts/Song Of Days Past.png';
import TenacityOfTheMillelith from '/public/icons/artifacts/Tenacity Of The Millelith.png';
import ThunderingFury from '/public/icons/artifacts/Thundering Fury.png';
import Thundersoother from '/public/icons/artifacts/Thundersoother.png';
import UnfinishedReverie from '/public/icons/artifacts/Unfinished Reverie.png';
import VermillionHereafter from '/public/icons/artifacts/Vermillion Hereafter.png';
import ViridescentVenerer from '/public/icons/artifacts/Viridescent Venerer.png';
import VourukashasGlow from '/public/icons/artifacts/Vourukasha\'s Glow.png';
import WanderersTroupe from '/public/icons/artifacts/Wanderer\'s Troupe.png';
export const artifacts = {
  ['Archaic Petra']: ArchaicPetra,
  ['Blizzard Strayer']: BlizzardStrayer,
  ['Bloodstained Chivalry']: BloodstainedChivalry,
  ['Crimson Witch Of Flames']: CrimsonWitchOfFlames,
  ['Deepwood Memories']: DeepwoodMemories,
  ['Desert Pavilion Chronicle']: DesertPavilionChronicle,
  ['Echoes Of An Offering']: EchoesOfAnOffering,
  ['Emblem Of Severed Fate']: EmblemOfSeveredFate,
  ['Flower Of Paradise Lost']: FlowerOfParadiseLost,
  ['Fragment Of Harmonic Whimsy']: FragmentOfHarmonicWhimsy,
  ['Gilded Dreams']: GildedDreams,
  ['Gladiator\'s Finale']: GladiatorsFinale,
  ['Golden Troupe']: GoldenTroupe,
  ['Heart Of Depth']: HeartOfDepth,
  ['Husk Of Opulent Dreams']: HuskOfOpulentDreams,
  ['Instructor']: Instructor,
  ['Lavawalker']: Lavawalker,
  ['Maiden Beloved']: MaidenBeloved,
  ['Marechaussee Hunter']: MarechausseeHunter,
  ['Nighttime Whispers In The Echoing Woods']: NighttimeWhispersInTheEchoingWoods,
  ['Noblesse Oblige']: NoblesseOblige,
  ['Nymph\'s Dream']: NymphsDream,
  ['Obsidian Codex']: ObsidianCodex,
  ['Ocean-Hued Clam']: OceanHuedClam,
  ['Pale Flame']: PaleFlame,
  ['Retracing Bolide']: RetracingBolide,
  ['Scroll Of The Hero Of Cinder City']: ScrollOfTheHeroOfCinderCity,
  ['Shimenawa\'s Reminiscence']: ShimenawasReminiscence,
  ['Song Of Days Past']: SongOfDaysPast,
  ['Tenacity Of The Millelith']: TenacityOfTheMillelith,
  ['Thundering Fury']: ThunderingFury,
  ['Thundersoother']: Thundersoother,
  ['Unfinished Reverie']: UnfinishedReverie,
  ['Vermillion Hereafter']: VermillionHereafter,
  ['Viridescent Venerer']: ViridescentVenerer,
  ['Vourukasha\'s Glow']: VourukashasGlow,
  ['Wanderer\'s Troupe']: WanderersTroupe
}


import Albedo from '/public/icons/characters/Albedo.png';
import Alhaitham from '/public/icons/characters/Alhaitham.png';
import Aloy from '/public/icons/characters/Aloy.png';
import Amber from '/public/icons/characters/Amber.png';
import AnemoTraveler from '/public/icons/characters/Anemo Traveler.png';
import AratakiItto from '/public/icons/characters/Arataki Itto.png';
import Arlecchino from '/public/icons/characters/Arlecchino.png';
import Baizhu from '/public/icons/characters/Baizhu.png';
import Barbara from '/public/icons/characters/Barbara.png';
import Beidou from '/public/icons/characters/Beidou.png';
import Charlotte from '/public/icons/characters/Charlotte.png';
import Chasca from '/public/icons/characters/Chasca.png';
import Chevreuse from '/public/icons/characters/Chevreuse.png';
import Chiori from '/public/icons/characters/Chiori.png';
import Chongyun from '/public/icons/characters/Chongyun.png';
import Citlali from '/public/icons/characters/Citlali.webp';
import Clorinde from '/public/icons/characters/Clorinde.png';
import Cyno from '/public/icons/characters/Cyno.png';
import Dehya from '/public/icons/characters/Dehya.png';
import Diluc from '/public/icons/characters/Diluc.png';
import Dori from '/public/icons/characters/Dori.png';
import Emilie from '/public/icons/characters/Emilie.png';
import Eula from '/public/icons/characters/Eula.png';
import Faruzan from '/public/icons/characters/Faruzan.png';
import Fischl from '/public/icons/characters/Fischl.png';
import Freminet from '/public/icons/characters/Freminet.png';
import Furina from '/public/icons/characters/Furina.png';
import Gaming from '/public/icons/characters/Gaming.png';
import Ganyu from '/public/icons/characters/Ganyu.png';
import Heizou from '/public/icons/characters/Heizou.png';
import HuTao from '/public/icons/characters/Hu Tao.png';
import HydroTraveler from '/public/icons/characters/Hydro Traveler.png';
import Jean from '/public/icons/characters/Jean.png';
import Kachina from '/public/icons/characters/Kachina.png';
import KaedeharaKazuha from '/public/icons/characters/Kaedehara Kazuha.png';
import Kaeya from '/public/icons/characters/Kaeya.png';
import KamisatoAyaka from '/public/icons/characters/Kamisato Ayaka.png';
import KamisatoAyato from '/public/icons/characters/Kamisato Ayato.png';
import Kaveh from '/public/icons/characters/Kaveh.png';
import Keqing from '/public/icons/characters/Keqing.png';
import Kinich from '/public/icons/characters/Kinich.png';
import Kirara from '/public/icons/characters/Kirara.png';
import Klee from '/public/icons/characters/Klee.png';
import KukiShinobu from '/public/icons/characters/Kuki Shinobu.png';
import LanYan from '/public/icons/characters/Lan Yan.webp';
import Layla from '/public/icons/characters/Layla.png';
import Lisa from '/public/icons/characters/Lisa.png';
import Lynette from '/public/icons/characters/Lynette.png';
import Lyney from '/public/icons/characters/Lyney.png';
import Mavuika from '/public/icons/characters/Mavuika.webp';
import Mona from '/public/icons/characters/Mona.png';
import Mualani from '/public/icons/characters/Mualani.png';
import Nahida from '/public/icons/characters/Nahida.png';
import Navia from '/public/icons/characters/Navia.png';
import Neuvilette from '/public/icons/characters/Neuvilette.png';
import Nilou from '/public/icons/characters/Nilou.png';
import Ningguang from '/public/icons/characters/Ningguang.png';
import Noelle from '/public/icons/characters/Noelle.png';
import Qiqi from '/public/icons/characters/Qiqi.png';
import RaidenShogun from '/public/icons/characters/Raiden Shogun.png';
import Razor from '/public/icons/characters/Razor.png';
import Rosaria from '/public/icons/characters/Rosaria.png';
import SangonomiyaKokomi from '/public/icons/characters/Sangonomiya Kokomi.png';
import Sayu from '/public/icons/characters/Sayu.png';
import Sethos from '/public/icons/characters/Sethos.png';
import Sigewinne from '/public/icons/characters/Sigewinne.png';
import Sucrose from '/public/icons/characters/Sucrose.png';
import Tartaglia from '/public/icons/characters/Tartaglia.png';
import Thoma from '/public/icons/characters/Thoma.png';
import Tighnari from '/public/icons/characters/Tighnari.png';
import Venti from '/public/icons/characters/Venti.png';
import Wanderer from '/public/icons/characters/Wanderer.png';
import Wriothesley from '/public/icons/characters/Wriothesley.png';
import Xiangling from '/public/icons/characters/Xiangling.png';
import Xianyun from '/public/icons/characters/Xianyun.png';
import Xiao from '/public/icons/characters/Xiao.png';
import Xilonen from '/public/icons/characters/Xilonen.png';
import Xinyan from '/public/icons/characters/Xinyan.png';
import YaeMiko from '/public/icons/characters/Yae Miko.png';
import Yanfei from '/public/icons/characters/Yanfei.png';
import Yaoyao from '/public/icons/characters/Yaoyao.png';
import Yoimiya from '/public/icons/characters/Yoimiya.png';
import YunJin from '/public/icons/characters/Yun Jin.png';
import Zhongli from '/public/icons/characters/Zhongli.png';
export const characters = {
  ['Albedo']: Albedo,
  ['Alhaitham']: Alhaitham,
  ['Aloy']: Aloy,
  ['Amber']: Amber,
  ['Anemo Traveler']: AnemoTraveler,
  ['Arataki Itto']: AratakiItto,
  ['Arlecchino']: Arlecchino,
  ['Baizhu']: Baizhu,
  ['Barbara']: Barbara,
  ['Beidou']: Beidou,
  ['Charlotte']: Charlotte,
  ['Chasca']: Chasca,
  ['Chevreuse']: Chevreuse,
  ['Chiori']: Chiori,
  ['Chongyun']: Chongyun,
  ['Citlali']: Citlali,
  ['Clorinde']: Clorinde,
  ['Cyno']: Cyno,
  ['Dehya']: Dehya,
  ['Diluc']: Diluc,
  ['Dori']: Dori,
  ['Emilie']: Emilie,
  ['Eula']: Eula,
  ['Faruzan']: Faruzan,
  ['Fischl']: Fischl,
  ['Freminet']: Freminet,
  ['Furina']: Furina,
  ['Gaming']: Gaming,
  ['Ganyu']: Ganyu,
  ['Heizou']: Heizou,
  ['Hu Tao']: HuTao,
  ['Hydro Traveler']: HydroTraveler,
  ['Jean']: Jean,
  ['Kachina']: Kachina,
  ['Kaedehara Kazuha']: KaedeharaKazuha,
  ['Kaeya']: Kaeya,
  ['Kamisato Ayaka']: KamisatoAyaka,
  ['Kamisato Ayato']: KamisatoAyato,
  ['Kaveh']: Kaveh,
  ['Keqing']: Keqing,
  ['Kinich']: Kinich,
  ['Kirara']: Kirara,
  ['Klee']: Klee,
  ['Kuki Shinobu']: KukiShinobu,
  ['Lan Yan']: LanYan,
  ['Layla']: Layla,
  ['Lisa']: Lisa,
  ['Lynette']: Lynette,
  ['Lyney']: Lyney,
  ['Mavuika']: Mavuika,
  ['Mona']: Mona,
  ['Mualani']: Mualani,
  ['Nahida']: Nahida,
  ['Navia']: Navia,
  ['Neuvilette']: Neuvilette,
  ['Nilou']: Nilou,
  ['Ningguang']: Ningguang,
  ['Noelle']: Noelle,
  ['Qiqi']: Qiqi,
  ['Raiden Shogun']: RaidenShogun,
  ['Razor']: Razor,
  ['Rosaria']: Rosaria,
  ['Sangonomiya Kokomi']: SangonomiyaKokomi,
  ['Sayu']: Sayu,
  ['Sethos']: Sethos,
  ['Sigewinne']: Sigewinne,
  ['Sucrose']: Sucrose,
  ['Tartaglia']: Tartaglia,
  ['Thoma']: Thoma,
  ['Tighnari']: Tighnari,
  ['Venti']: Venti,
  ['Wanderer']: Wanderer,
  ['Wriothesley']: Wriothesley,
  ['Xiangling']: Xiangling,
  ['Xianyun']: Xianyun,
  ['Xiao']: Xiao,
  ['Xilonen']: Xilonen,
  ['Xinyan']: Xinyan,
  ['Yae Miko']: YaeMiko,
  ['Yanfei']: Yanfei,
  ['Yaoyao']: Yaoyao,
  ['Yoimiya']: Yoimiya,
  ['Yun Jin']: YunJin,
  ['Zhongli']: Zhongli
}
